import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const manrope = Manrope({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${manrope.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-[#070c12] text-white">
        <Navbar />
        <main>
          {children}
        </main>
        <hr></hr>
        <Footer/>
      </body>
    </html>
  );
}
